# Generated by Django 4.2.13 on 2026-08-06 03:43

import apps.certificates.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('attempts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Sertifikat raqami')),
                ('verify_token', models.CharField(default=apps.certificates.models._make_verify_token, max_length=64, unique=True, verbose_name='Tekshiruv tokeni')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ism va familiya')),
                ('exam_title', models.CharField(max_length=150, verbose_name='Test nomi')),
                ('exam_date', models.DateField(verbose_name='Test sanasi')),
                ('ball', models.FloatField(default=0.0, verbose_name='RASH balli')),
                ('max_ball', models.FloatField(default=90.14, verbose_name='Maksimal ball')),
                ('percent', models.FloatField(blank=True, null=True, verbose_name='Foiz')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='Daraja')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="Reyting o'rni")),
                ('total_participants', models.PositiveIntegerField(default=0, verbose_name='Jami qatnashchilar')),
                ('section_scores', models.JSONField(blank=True, default=dict, verbose_name="Bo'limlar natijasi")),
                ('organization', models.CharField(blank=True, default='', max_length=150, verbose_name='Tashkilot')),
                ('organizer_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Tashkilotchi')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Berilgan sana')),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/', verbose_name='PDF fayl')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='Bekor qilingan')),
                ('revoke_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Bekor qilish sababi')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='Yuklab olishlar soni')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='attempts.attempt', verbose_name='Urinish')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='exams.exam', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.botuser', verbose_name='Qatnashchi')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ('-issued_at',),
                'indexes': [models.Index(fields=['exam', '-ball'], name='certificate_exam_id_2b1fa5_idx')],
            },
        ),
    ]
