# Generated by Django 4.2.13 on 2026-08-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='award_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Sertifikat foizi'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name="To'g'ri javob foizi"),
        ),
    ]
