# Generated by Django 4.2.13 on 2026-08-06 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('participants', models.PositiveIntegerField(default=0, verbose_name='Qatnashchilar soni')),
                ('avg_raw_score', models.FloatField(default=0.0, verbose_name="O'rtacha xom ball")),
                ('avg_percent', models.FloatField(default=0.0, verbose_name="O'rtacha foiz")),
                ('avg_ball', models.FloatField(default=0.0, verbose_name="O'rtacha standart ball")),
                ('max_ball_achieved', models.FloatField(default=0.0, verbose_name='Eng yuqori ball')),
                ('min_ball_achieved', models.FloatField(default=0.0, verbose_name='Eng past ball')),
                ('std_ball', models.FloatField(default=0.0, verbose_name="Ballar standart og'ishi")),
                ('reliability', models.FloatField(default=0.0, verbose_name='Ishonchlilik (KR-20 / Rasch)')),
                ('grade_distribution', models.JSONField(blank=True, default=dict, verbose_name='Darajalar taqsimoti')),
                ('item_statistics', models.JSONField(blank=True, default=list, verbose_name='Savollar statistikasi')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='exams.exam', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Test statistikasi',
                'verbose_name_plural': 'Testlar statistikasi',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Ism va familiya')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('draft', 'Jarayonda'), ('submitted', 'Yuborilgan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='draft', max_length=12, verbose_name='Holati')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan vaqt')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='Sarflangan vaqt (sek)')),
                ('current_order', models.PositiveIntegerField(default=1, verbose_name='Joriy savol raqami')),
                ('raw_score', models.FloatField(default=0.0, verbose_name="Xom ball (to'g'ri qismlar)")),
                ('max_raw_score', models.FloatField(default=0.0, verbose_name='Maksimal xom ball')),
                ('percent', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('wrong_count', models.PositiveIntegerField(default=0, verbose_name='Xato javoblar')),
                ('empty_count', models.PositiveIntegerField(default=0, verbose_name="Bo'sh javoblar")),
                ('theta', models.FloatField(blank=True, null=True, verbose_name='Rasch theta')),
                ('theta_se', models.FloatField(blank=True, null=True, verbose_name='theta standart xatosi')),
                ('ball', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Standart ball')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='Daraja')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name="Reyting o'rni")),
                ('section_scores', models.JSONField(blank=True, default=dict, verbose_name="Bo'limlar bo'yicha natija")),
                ('is_scored', models.BooleanField(default=False, verbose_name='Baholangan')),
                ('scored_at', models.DateTimeField(blank=True, null=True, verbose_name='Baholangan vaqt')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='exams.exam', verbose_name='Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='users.botuser', verbose_name='Ishtirokchi')),
            ],
            options={
                'verbose_name': 'Urinish',
                'verbose_name_plural': 'Urinishlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Savol tartibi')),
                ('selected', models.CharField(blank=True, default='', help_text="SINGLE: A. MULTI: ABD ko'rinishida.", max_length=8, verbose_name='Tanlangan variant(lar)')),
                ('text_a', models.CharField(blank=True, default='', max_length=255, verbose_name='a) javob')),
                ('text_b', models.CharField(blank=True, default='', max_length=255, verbose_name='b) javob')),
                ('is_correct_a', models.BooleanField(blank=True, null=True, verbose_name="1-qism to'g'ri")),
                ('is_correct_b', models.BooleanField(blank=True, null=True, verbose_name="2-qism to'g'ri")),
                ('score', models.FloatField(default=0.0, verbose_name='Olingan ball')),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Javob vaqti')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt', verbose_name='Urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ('attempt_id', 'order'),
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', 'status'], name='attempts_at_exam_id_6a09b3_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', '-created_at'], name='attempts_at_user_id_7af9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', '-ball'], name='attempts_at_exam_id_d958c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'submitted')), fields=('exam', 'user'), name='uniq_submitted_attempt_per_user'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_answer_per_question'),
        ),
    ]
