# Generated by Django 4.2.13 on 2026-09-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_exam_certificate_min_percent'),
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ism va familiya')),
                ('ball', models.FloatField(verbose_name='Standart ball')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='Daraja')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_participants', to='exams.exam', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Soxta qatnashchi',
                'verbose_name_plural': 'Soxta qatnashchilar',
                'ordering': ('-ball', 'order'),
                'indexes': [models.Index(fields=['exam', '-ball'], name='attempts_mo_exam_id_a71467_idx')],
            },
        ),
    ]
