# Generated by Django 4.2.13 on 2026-09-07 05:22

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion


def backfill_final_ball(apps, schema_editor):
    """
    Eski yozuvlarda yakuniy ball test balliga teng.

    Esse maydonlari yangi qo'shilgani uchun mavjud urinishlarda esse
    balli yo'q — demak yakuniy ball test ballining o'zi. Reyting va
    daraja shu maydonga tayangani uchun uni to'ldirib qo'yamiz.
    """
    Attempt = apps.get_model("attempts", "Attempt")
    Attempt.objects.filter(ball__isnull=False, final_ball__isnull=True).update(
        final_ball=F("ball")
    )


def noop(apps, schema_editor):
    """Orqaga qaytishda hech narsa qilinmaydi — maydon o'chib ketadi."""


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_esse_va_soxta_qatorlar'),
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhantomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('full_name', models.CharField(max_length=120, verbose_name='Ism va familiya')),
                ('raw_score', models.FloatField(default=0.0, verbose_name='Xom ball')),
                ('max_raw_score', models.FloatField(default=0.0, verbose_name='Maksimal xom ball')),
                ('percent', models.FloatField(default=0.0, verbose_name='Foiz')),
                ('ball', models.FloatField(blank=True, null=True, verbose_name='Yakuniy ball')),
                ('grade', models.CharField(blank=True, default='', max_length=16, verbose_name='Daraja')),
            ],
            options={
                'verbose_name': "Soxta qatnashchi (e'lon uchun)",
                'verbose_name_plural': "Soxta qatnashchilar (e'lon uchun)",
                'ordering': ('-ball', '-raw_score', 'id'),
            },
        ),
        migrations.AddField(
            model_name='attempt',
            name='essay_ball',
            field=models.FloatField(blank=True, null=True, verbose_name='Esse balli'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='final_ball',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Yakuniy ball'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='ball',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Test balli'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['exam', '-final_ball'], name='attempts_at_exam_id_e4b828_idx'),
        ),
        migrations.AddField(
            model_name='phantomparticipant',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phantoms', to='exams.exam', verbose_name='Test'),
        ),
        migrations.AddIndex(
            model_name='phantomparticipant',
            index=models.Index(fields=['exam', '-ball'], name='attempts_ph_exam_id_2ea092_idx'),
        ),
        migrations.AddConstraint(
            model_name='phantomparticipant',
            constraint=models.UniqueConstraint(fields=('exam', 'full_name'), name='uniq_phantom_name_per_exam'),
        ),
        migrations.RunPython(backfill_final_ball, noop),
    ]
