# Generated by Django 4.2.13 on 2026-08-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Telegram username')),
                ('tg_first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Telegram ismi')),
                ('tg_last_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Telegram familiyasi')),
                ('full_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Ism va familiya')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon raqami')),
                ('is_registered', models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan")),
                ('registered_at', models.DateTimeField(blank=True, null=True, verbose_name="Ro'yxatdan o'tgan vaqt")),
                ('is_admin', models.BooleanField(default=False, verbose_name='Asosiy admin')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Bloklangan')),
                ('block_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Bloklash sababi')),
                ('is_subscribed', models.BooleanField(default=False, verbose_name="Kanalga a'zo")),
                ('subscription_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Obuna tekshirilgan vaqt')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('register', "Ro'yxatdan o'tdi"), ('exam_created', 'Test yaratdi'), ('exam_published', "Natijalarni e'lon qildi"), ('attempt_started', 'Testni boshladi'), ('attempt_submitted', 'Javoblarni yubordi'), ('code_activated', 'ID kodni faollashtirdi'), ('code_used', 'ID kodni ishlatdi'), ('codes_generated', 'ID kodlar yaratdi'), ('cert_issued', 'Sertifikat oldi'), ('other', 'Boshqa')], default='other', max_length=32, verbose_name='Amal')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Tavsif')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Amal tarixi',
                'verbose_name_plural': 'Amallar tarixi',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['is_registered'], name='users_botus_is_regi_12e54d_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['is_admin'], name='users_botus_is_admi_81c1bc_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['kind', '-created_at'], name='users_usera_kind_32f5d2_idx'),
        ),
    ]
