# Generated by Django 4.2.13 on 2026-08-06 03:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title', models.CharField(max_length=150, verbose_name='Test nomi')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Test kodi')),
                ('exam_type', models.CharField(choices=[('simple', '1-tur — Oddiy test'), ('rasch_free', '2-tur — Bepul RASH testi'), ('rasch_paid', '3-tur — Pullik RASH testi')], db_index=True, default='simple', max_length=16, verbose_name='Test turi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('active', 'Faol (javoblar qabul qilinmoqda)'), ('closed', 'Yopilgan'), ('calculated', 'Natijalar hisoblangan'), ('published', "Natijalar e'lon qilingan"), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=16, verbose_name='Holati')),
                ('description', models.TextField(blank=True, default='', verbose_name='Tavsif')),
                ('question_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Savollar soni')),
                ('is_national_template', models.BooleanField(default=False, verbose_name='Milliy sertifikat shabloni (45 ta savol)')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Davomiyligi (daqiqa, 0 = cheklanmagan)')),
                ('is_public', models.BooleanField(default=True, verbose_name="Ommaviy ro'yxatda ko'rinsin")),
                ('show_results_to_participants', models.BooleanField(default=True, verbose_name="Natija qatnashchilarga ko'rinsin")),
                ('show_correct_answers', models.BooleanField(default=True, verbose_name="To'g'ri/xato javoblar ko'rsatilsin")),
                ('show_rating_to_participants', models.BooleanField(default=True, verbose_name="Reyting qatnashchilarga ko'rinsin")),
                ('max_ball', models.FloatField(default=90.14, verbose_name='Maksimal standart ball')),
                ('theta_min', models.FloatField(default=-4.0, verbose_name='theta quyi chegara')),
                ('theta_max', models.FloatField(default=4.0, verbose_name='theta yuqori chegara')),
                ('auto_calibrate', models.BooleanField(default=True, verbose_name="Savol qiyinligi ma'lumotlardan hisoblansin (JMLE)")),
                ('certificate_enabled', models.BooleanField(default=False, verbose_name='Sertifikat berilsinmi')),
                ('certificate_scope', models.CharField(choices=[('all', 'Barcha qatnashchilarga'), ('min_ball', "Belgilangan balldan yuqori bo'lganlarga"), ('min_grade', "Belgilangan darajadan yuqori bo'lganlarga")], default='all', max_length=16, verbose_name='Sertifikat kimlarga')),
                ('certificate_min_ball', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Minimal ball')),
                ('certificate_min_grade', models.CharField(blank=True, default='', max_length=8, verbose_name='Minimal daraja')),
                ('organizer_name', models.CharField(blank=True, default='', max_length=120, verbose_name="Tashkilotchi / o'qituvchi")),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Hisoblangan vaqt')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name="E'lon qilingan vaqt")),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Yopilgan vaqt')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.botuser', verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('order', models.PositiveIntegerField(db_index=True, verbose_name='Tartib raqami')),
                ('kind', models.CharField(choices=[('single', 'Bitta javobli (A–D)'), ('multi', "Ko'p javobli (A–F)"), ('open', 'Ochiq javob (a, b)')], default='single', max_length=8, verbose_name='Turi')),
                ('text', models.TextField(blank=True, default='', verbose_name='Savol matni')),
                ('section', models.CharField(blank=True, default='', max_length=64, verbose_name="Bo'lim")),
                ('choices_count', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='Variantlar soni')),
                ('correct_key', models.CharField(blank=True, default='', help_text="SINGLE uchun: A. MULTI uchun: ABD ko'rinishida.", max_length=8, verbose_name="To'g'ri javob kaliti")),
                ('answer_a', models.CharField(blank=True, default='', help_text='Matematik ifoda; SymPy orqali ekvivalentlikka tekshiriladi.', max_length=255, verbose_name='a) javob')),
                ('answer_b', models.CharField(blank=True, default='', max_length=255, verbose_name='b) javob')),
                ('numeric_tolerance', models.FloatField(default=1e-06, help_text='Sonli javoblarni taqqoslashda ruxsat etilgan farq.', verbose_name='Sonli xatolik chegarasi')),
                ('parts', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Ballanadigan qismlar soni')),
                ('difficulty', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Qiyinlik b (1-qism)')),
                ('difficulty_b', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-5.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Qiyinlik b (2-qism)')),
                ('difficulty_locked', models.BooleanField(default=False, verbose_name="Qiyinlik qo'lda kiritilgan (avtomatik o'zgartirilmasin)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ('exam_id', 'order'),
            },
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('exam', 'order'), name='uniq_exam_question_order'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_type', 'status'], name='exams_exam_exam_ty_975df5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['owner', '-created_at'], name='exams_exam_owner_i_087d59_idx'),
        ),
    ]
