# Generated by Django 4.2.13 on 2026-08-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedExamCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Test kodi')),
                ('exam_title', models.CharField(blank=True, default='', max_length=150, verbose_name='Qaysi test uchun')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
            ],
            options={
                'verbose_name': 'Band qilingan test kodi',
                'verbose_name_plural': 'Band qilingan test kodlari',
                'ordering': ('-created_at',),
            },
        ),
    ]
