# Generated by Django 4.2.13 on 2026-08-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_reservedexamcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='closed_report_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yopilish hisoboti yuborilgan vaqt'),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_report_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="E'lon hisoboti yuborilgan vaqt"),
        ),
    ]
