# Generated by Django 4.2.13 on 2026-08-09 06:10
#
# Test kodi endi qayta ishlatiladi: test yakunlangach («yopilgan»,
# «hisoblangan», «e'lon qilingan» yoki «arxivlangan») uning kodi bo'shaydi
# va bot uni yangi testga bera oladi. Shu sababli:
#
#   * `ReservedExamCode.released_at` — kod qachon bo'shaganini belgilaydi;
#   * `Exam.code` global `unique` emas — cheklov faqat yakunlanmagan
#     testlar orasida ishlaydi (`uniq_live_exam_code`);
#   * mavjud yakunlangan testlarning kodlari darhol bo'shatiladi.

from django.db import migrations, models
from django.utils import timezone

#: Kod band hisoblanadigan holatlar.
LIVE_STATUSES = ("draft", "active")


def release_finished_codes(apps, schema_editor):
    """Yakunlangan testlarning kodlarini umumiy fondga qaytaradi."""
    Exam = apps.get_model("exams", "Exam")
    ReservedExamCode = apps.get_model("exams", "ReservedExamCode")

    live = set(
        Exam.objects.filter(status__in=LIVE_STATUSES).values_list("code", flat=True)
    )
    ReservedExamCode.objects.filter(released_at__isnull=True).exclude(
        code__in=live
    ).update(released_at=timezone.now())


def hold_all_codes(apps, schema_editor):
    """Ortga qaytarish: barcha kodlar yana band holatiga o'tadi."""
    ReservedExamCode = apps.get_model("exams", "ReservedExamCode")
    ReservedExamCode.objects.update(released_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_closed_report_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservedexamcode',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Bo'shatilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='exam',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Test kodi'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'active'))), fields=('code',), name='uniq_live_exam_code'),
        ),
        migrations.RunPython(release_finished_codes, hold_all_codes),
    ]
