# Generated by Django 4.2.13 on 2026-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_simple_codes_for_live_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_key',
            field=models.CharField(blank=True, default='', help_text='Bitta harf: A. Moslashtirish savollarida ham bitta harf (A–F).', max_length=8, verbose_name="To'g'ri javob kaliti"),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('single', 'Bitta javobli (A–D)'), ('multi', 'Moslashtirish (A–F)'), ('open', 'Ochiq javob (a, b)')], default='single', max_length=8, verbose_name='Turi'),
        ),
    ]
