# Generated by Django 4.2.13 on 2026-08-21 09:50

import django.core.validators
from django.db import migrations, models


def _apply_percent_scope(apps, schema_editor):
    """Mavjud testlarni ham 40% shartiga o'tkazadi.

    Ilgari standart qiymat «barchaga» edi, ya'ni daraja olmagan qatnashchi
    ham sertifikat olardi. Ataylab minimal ball yoki daraja tanlangan
    testlarga tegilmaydi.
    """
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.filter(certificate_scope="all").update(
        certificate_scope="min_percent", certificate_min_percent=40.0
    )


def _revert_percent_scope(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.filter(certificate_scope="min_percent").update(certificate_scope="all")


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_question_correct_key_alter_question_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='certificate_min_percent',
            field=models.FloatField(blank=True, default=40.0, help_text="To'g'ri javoblarning ulushi. Bo'sh qoldirilsa foiz sharti qo'llanmaydi.", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name="Minimal to'g'ri javob foizi"),
        ),
        migrations.AlterField(
            model_name='exam',
            name='certificate_scope',
            field=models.CharField(choices=[('all', 'Barcha qatnashchilarga'), ('min_percent', "To'g'ri javob foizi yetarli bo'lganlarga"), ('min_ball', "Belgilangan balldan yuqori bo'lganlarga"), ('min_grade', "Belgilangan darajadan yuqori bo'lganlarga")], default='min_percent', max_length=16, verbose_name='Sertifikat kimlarga'),
        ),
        migrations.RunPython(_apply_percent_scope, _revert_percent_scope),
    ]
