# Generated by Django 4.2.13 on 2026-08-21 12:07

import django.core.validators
from django.db import migrations, models


def _lower_threshold(apps, schema_editor):
    """Eski standart chegarani (40%) yangisiga (32%) o'tkazadi.

    55 ballik milliy shablonda 18 ta to'g'ri javob 32.7% ga to'g'ri keladi —
    C darajasi shu yerdan boshlanadi. Admin ataylab boshqa qiymat qo'ygan
    testlarga tegilmaydi.
    """
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.filter(certificate_min_percent=40.0).update(certificate_min_percent=32.0)


def _restore_threshold(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.filter(certificate_min_percent=32.0).update(certificate_min_percent=40.0)


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_certificate_min_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='certificate_min_percent',
            field=models.FloatField(blank=True, default=32.0, help_text="To'g'ri javoblarning ulushi. Bo'sh qoldirilsa foiz sharti qo'llanmaydi.", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name="Minimal to'g'ri javob foizi"),
        ),
        migrations.RunPython(_lower_threshold, _restore_threshold),
    ]
