# Generated by Django 4.2.13 on 2026-08-21 12:28

from django.db import migrations, models


def _grade_scope(apps, schema_editor):
    """Mavjud testlarni daraja shartiga o'tkazadi.

    0-45.9 ball — daraja olinmaydi, shuning uchun sertifikat ham
    berilmaydi. Ilgari shart to'g'ri javob foizi (32%) edi, lekin qiyin
    testda 32% to'g'ri javob 46 balldan past ballga to'g'ri kelishi va
    darajasiz sertifikat chiqishi mumkin edi.

    Admin ataylab minimal ball yoki boshqa foiz qo'ygan testlarga
    tegilmaydi.
    """
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.filter(certificate_scope__in=("min_percent", "all")).update(
        certificate_scope="min_grade", certificate_min_grade="C"
    )


def _percent_scope(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Exam.objects.filter(certificate_scope="min_grade", certificate_min_grade="C").update(
        certificate_scope="min_percent"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_alter_exam_certificate_min_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='certificate_min_grade',
            field=models.CharField(blank=True, default='C', help_text="Sertifikat shu darajadan boshlab beriladi. Bo'sh qoldirilsa daraja sharti qo'llanmaydi.", max_length=8, verbose_name='Minimal daraja'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='certificate_scope',
            field=models.CharField(choices=[('all', 'Barcha qatnashchilarga'), ('min_percent', "To'g'ri javob foizi yetarli bo'lganlarga"), ('min_ball', "Belgilangan balldan yuqori bo'lganlarga"), ('min_grade', "Belgilangan darajadan yuqori bo'lganlarga")], default='min_grade', max_length=16, verbose_name='Sertifikat kimlarga'),
        ),
        migrations.RunPython(_grade_scope, _percent_scope),
    ]
