# Generated by Django 4.2.13 on 2026-08-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_exam_certificate_min_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='anchor_scale',
            field=models.BooleanField(default=True, help_text="Savollarning 32% ini topgan qatnashchi «C» darajasining quyi chegarasini (46 ball) oladi. O'chirilsa, shkala qat'iy [-4; +4] oralig'ida qoladi.", verbose_name='Ball shkalasi darajaga moslansin'),
        ),
    ]
