# Generated by Django 4.2.13 on 2026-09-04 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_anchor_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='certificate_min_percent',
            field=models.FloatField(blank=True, default=29.0, help_text="To'g'ri javoblarning ulushi. Bo'sh qoldirilsa foiz sharti qo'llanmaydi.", null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name="Minimal to'g'ri javob foizi"),
        ),
    ]
