# Generated by Django 4.2.13 on 2026-08-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_exam_anchor_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_a',
            field=models.CharField(blank=True, default='', help_text="Javob matni. Bir nechta to'g'ri javobni «;» bilan ajrating (masalan: ot; ism). Tekshiruvda katta-kichik harf, apostrof ko'rinishi va tinish belgilari e'tiborga olinmaydi.", max_length=255, verbose_name='a) javob'),
        ),
        migrations.AlterField(
            model_name='question',
            name='numeric_tolerance',
            field=models.FloatField(default=1e-06, help_text='Eski maydon — ona tili testlarida ishlatilmaydi.', verbose_name='Sonli xatolik chegarasi'),
        ),
    ]
