# Generated by Django 4.2.13 on 2026-09-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_question_answer_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_a',
            field=models.CharField(blank=True, default='', help_text="Javob matni. Sinonimlarni vergul bilan sanang (masalan: osmon, samo, fazo) — har biri to'g'ri hisoblanadi. Tekshiruvda katta-kichik harf, apostrof (hatto uning yo'qligi: orta = o‘rta) va tinish belgilari e'tiborga olinmaydi.", max_length=255, verbose_name='a) javob'),
        ),
    ]
