# Generated by Django 4.2.13 on 2026-09-07 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_sinonim_izohi'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='essay_enabled',
            field=models.BooleanField(default=False, help_text='Yoqilsa yakuniy ball = (test balli + esse balli) / 2. Esse balli har bir qatnashchi uchun panelda kiritiladi.', verbose_name='Esse baholansinmi'),
        ),
        migrations.AddField(
            model_name='exam',
            name='essay_max_ball',
            field=models.FloatField(default=90.14, help_text="Esse shu shkalada baholanadi. Test shkalasidan farq qilsa, qo'shishdan oldin avtomatik moslashtiriladi.", validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000.0)], verbose_name='Esse uchun maksimal ball'),
        ),
    ]
