# Generated by Django 4.2.13 on 2026-09-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_esse_va_soxta_qatorlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_national_template',
            field=models.BooleanField(default=False, verbose_name='Milliy sertifikat shabloni (44 ta savol)'),
        ),
    ]
