# Generated by Django 4.2.13 on 2026-08-06 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('attempts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Kodlar soni')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Izoh')),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/codes/', verbose_name='Excel fayl')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_batches', to='users.botuser', verbose_name='Yaratuvchi')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_batches', to='exams.exam', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'ID kodlar partiyasi',
                'verbose_name_plural': 'ID kodlar partiyalari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='ID kod')),
                ('status', models.CharField(choices=[('unused', 'Ishlatilmagan'), ('activated', 'Faollashtirilgan'), ('used', 'Ishlatilgan'), ('revoked', 'Bekor qilingan')], db_index=True, default='unused', max_length=12, verbose_name='Holati')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Ism va familiya')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Faollashtirilgan vaqt')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan vaqt')),
                ('attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_code', to='attempts.attempt', verbose_name='Urinish')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='accesscodes.codebatch', verbose_name='Partiya')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_codes', to='exams.exam', verbose_name='Test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_codes', to='users.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'ID kod',
                'verbose_name_plural': 'ID kodlar',
                'ordering': ('exam_id', 'id'),
                'indexes': [models.Index(fields=['exam', 'status'], name='accesscodes_exam_id_0c6764_idx'), models.Index(fields=['telegram_id'], name='accesscodes_telegra_4e4357_idx')],
            },
        ),
    ]
