# Generated by Django 4.2.13 on 2026-08-25 03:03

import apps.broadcasts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('exams', '0010_exam_anchor_scale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('title', models.CharField(blank=True, default='', max_length=150, verbose_name='Sarlavha (faqat panel uchun)')),
                ('text', models.TextField(blank=True, default='', verbose_name='Xabar matni')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.broadcasts.models.broadcast_image_path, verbose_name='Rasm')),
                ('image_file_id', models.CharField(blank=True, default='', max_length=256, verbose_name='Telegram fayl belgisi')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='Tugmalar')),
                ('audience', models.CharField(choices=[('all', 'Barcha foydalanuvchilar'), ('registered', "Ro'yxatdan o'tganlar"), ('active', "Oxirgi 30 kunda faol bo'lganlar"), ('admins', 'Faqat adminlar'), ('exam', 'Tanlangan test ishtirokchilari')], default='all', max_length=16, verbose_name='Kimga')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('queued', 'Navbatda'), ('sending', 'Yuborilmoqda'), ('done', 'Yakunlandi'), ('cancelled', "To'xtatildi"), ('failed', 'Xato')], db_index=True, default='draft', max_length=12, verbose_name='Holati')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="Bo'sh bo'lsa darhol yuboriladi.", null=True, verbose_name='Rejalashtirilgan vaqt')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Qabul qiluvchilar')),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='Yuborildi')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Yuborilmadi')),
                ('blocked', models.PositiveIntegerField(default=0, verbose_name='Botni bloklaganlar')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Boshlangan vaqt')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan vaqt')),
                ('error', models.CharField(blank=True, default='', max_length=255, verbose_name='Xato')),
                ('test_target_id', models.BigIntegerField(blank=True, null=True, verbose_name='Sinov uchun Telegram ID')),
                ('test_requested_at', models.DateTimeField(blank=True, null=True, verbose_name="Sinov so'ralgan vaqt")),
                ('test_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sinov yuborilgan vaqt')),
                ('test_error', models.CharField(blank=True, default='', max_length=255, verbose_name='Sinov xatosi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to='exams.exam', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Reklama xabari',
                'verbose_name_plural': 'Reklama xabarlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BroadcastDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborildi'), ('failed', 'Yuborilmadi'), ('blocked', 'Botni bloklagan')], default='pending', max_length=10, verbose_name='Holati')),
                ('error', models.CharField(blank=True, default='', max_length=200, verbose_name='Xato')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqt')),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='broadcasts.broadcast', verbose_name='Reklama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to='users.botuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuborish',
                'verbose_name_plural': 'Yuborishlar',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['broadcast', 'status'], name='broadcasts__broadca_714699_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='broadcastdelivery',
            constraint=models.UniqueConstraint(fields=('broadcast', 'user'), name='broadcast_user_unique'),
        ),
        migrations.AddIndex(
            model_name='broadcast',
            index=models.Index(fields=['status', 'scheduled_at'], name='broadcasts__status_4facc0_idx'),
        ),
    ]
